window.FP_VOCAB_TEXT = [
  'PET|/ˌpiː iː ˈtiː/|聚对苯二甲酸乙二醇酯|material',
  'PETG|/ˌpiː iː tiː ˈdʒiː/|聚对苯二甲酸乙二醇酯共聚物|material',
  'APET|/ˌeɪ piː iː ˈtiː/|非结晶 PET|material',
  'RPET|/ˌɑːr piː iː ˈtiː/|再生 PET|material',
  'PLA|/ˌpiː el ˈeɪ/|聚乳酸|material',
  'PP|/ˌpiː ˈpiː/|聚丙烯|material',
  'PE|/ˌpiː ˈiː/|聚乙烯|material',
  'HDPE|/ˌeɪtʃ diː piː ˈiː/|高密度聚乙烯|material',
  'LDPE|/ˌel diː piː ˈiː/|低密度聚乙烯|material',
  'ABS|/ˌeɪ biː ˈes/|丙烯腈-丁二烯-苯乙烯|material',
  'ASA|/ˌeɪ es ˈeɪ/|丙烯腈-苯乙烯-丙烯酸酯|material',
  'PC|/ˌpiː ˈsiː/|聚碳酸酯|material',
  'PA|/ˌpiː ˈeɪ/|聚酰胺/尼龙|material',
  'TPU|/ˌtiː piː ˈjuː/|热塑性聚氨酯|material',
  'resin|/ˈrezɪn/|树脂|material',
  'polymer|/ˈpɒlɪmə(r)/|聚合物|material',
  'carrier resin|/ˈkæriə ˈrezɪn/|载体树脂|material',
  'recycled content|/ˌriːˈsaɪkəld ˈkɒntent/|再生成分含量|material',
  'virgin resin|/ˈvɜːdʒɪn ˈrezɪn/|原生树脂|material',
  'crystallinity|/ˌkrɪstəˈlɪnəti/|结晶度|material',
  'glass transition temperature|/ɡlɑːs trænˈzɪʃən ˈtemprətʃə/|玻璃化转变温度|material',
  'melting point|/ˈmeltɪŋ pɔɪnt/|熔点|material',
  'intrinsic viscosity|/ɪnˈtrɪnsɪk vɪˈskɒsəti/|特性黏度|material',
  'melt flow index|/melt fləʊ ˈɪndeks/|熔体流动指数|material',
  'moisture content|/ˈmɔɪstʃə ˈkɒntent/|含水率|material',
  'density|/ˈdensəti/|密度|material',
  'transparency|/trænsˈpærənsi/|透明度|material',
  'rigidity|/rɪˈdʒɪdəti/|刚性|material',
  'flexibility|/ˌfleksəˈbɪləti/|柔韧性|material',
  'toughness|/ˈtʌfnəs/|韧性|material',
  'impact strength|/ˈɪmpækt streŋθ/|冲击强度|material',
  'masterbatch|/ˈmɑːstəbætʃ/|母粒|additive',
  'color masterbatch|/ˈkʌlə ˈmɑːstəbætʃ/|色母粒|additive',
  'additive masterbatch|/ˈædətɪv ˈmɑːstəbætʃ/|功能母粒|additive',
  'slip agent|/slɪp ˈeɪdʒənt/|爽滑剂|additive',
  'anti-block agent|/ˌænti ˈblɒk ˈeɪdʒənt/|防粘剂|additive',
  'yellowing reducer|/ˈjeləʊɪŋ rɪˈdjuːsə/|消黄剂|additive',
  'optical brightener|/ˈɒptɪkəl ˈbraɪtənə/|荧光增白剂|additive',
  'toughening agent|/ˈtʌfənɪŋ ˈeɪdʒənt/|增韧剂|additive',
  'chain extender|/tʃeɪn ɪkˈstendə/|扩链剂|additive',
  'UV stabilizer|/ˌjuː ˈviː ˈsteɪbəlaɪzə/|紫外线稳定剂|additive',
  'antioxidant|/ˌæntiˈɒksɪdənt/|抗氧剂|additive',
  'antistatic agent|/ˌæntiˈstætɪk ˈeɪdʒənt/|抗静电剂|additive',
  'anti-fog agent|/ˌænti ˈfɒɡ ˈeɪdʒənt/|防雾剂|additive',
  'nucleating agent|/ˈnjuːklieɪtɪŋ ˈeɪdʒənt/|成核剂|additive',
  'flame retardant|/fleɪm rɪˈtɑːdənt/|阻燃剂|additive',
  'processing aid|/ˈprəʊsesɪŋ eɪd/|加工助剂|additive',
  'compatibilizer|/kəmˈpætəbəlaɪzə/|相容剂|additive',
  'dispersant|/dɪˈspɜːsənt/|分散剂|additive',
  'lubricant|/ˈluːbrɪkənt/|润滑剂|additive',
  'release agent|/rɪˈliːs ˈeɪdʒənt/|脱模剂|additive',
  'matting agent|/ˈmætɪŋ ˈeɪdʒənt/|消光剂|additive',
  'filler|/ˈfɪlə/|填料|additive',
  'active ingredient|/ˈæktɪv ɪnˈɡriːdiənt/|有效成分|additive',
  'loading level|/ˈləʊdɪŋ ˈlevəl/|有效成分含量|additive',
  'dosage|/ˈdəʊsɪdʒ/|添加量|additive',
  'migration|/maɪˈɡreɪʃən/|迁移|additive',
  'blooming|/ˈbluːmɪŋ/|析出/喷霜|additive',
  'dispersion|/dɪˈspɜːʃən/|分散性|additive',
  'compatibility|/kəmˌpætəˈbɪləti/|相容性|additive',
  'extrusion|/ɪkˈstruːʒən/|挤出|production',
  'extruder|/ɪkˈstruːdə/|挤出机|production',
  'hopper|/ˈhɒpə/|料斗|production',
  'screw|/skruː/|螺杆|production',
  'barrel|/ˈbærəl/|机筒|production',
  'die|/daɪ/|模头|production',
  'melt|/melt/|熔体|production',
  'pellet|/ˈpelɪt/|粒料|production',
  'granule|/ˈɡrænjuːl/|颗粒|production',
  'sheet|/ʃiːt/|片材|production',
  'film|/fɪlm/|薄膜|production',
  'thermoforming|/ˌθɜːməʊˈfɔːmɪŋ/|热成型|production',
  'injection molding|/ɪnˈdʒekʃən ˈməʊldɪŋ/|注塑成型|production',
  'blow molding|/bləʊ ˈməʊldɪŋ/|吹塑成型|production',
  'drying|/ˈdraɪɪŋ/|干燥|production',
  'dehumidifier|/ˌdiːhjuːˈmɪdɪfaɪə/|除湿干燥机|production',
  'feeding system|/ˈfiːdɪŋ ˈsɪstəm/|喂料系统|production',
  'screen changer|/skriːn ˈtʃeɪndʒə/|换网器|production',
  'winding|/ˈwaɪndɪŋ/|收卷|production',
  'output|/ˈaʊtpʊt/|产量|production',
  'throughput|/ˈθruːpʊt/|单位时间产量|production',
  'line speed|/laɪn spiːd/|线速度|production',
  'processing temperature|/ˈprəʊsesɪŋ ˈtemprətʃə/|加工温度|production',
  'residence time|/ˈrezɪdəns taɪm/|停留时间|production',
  'cooling roll|/ˈkuːlɪŋ rəʊl/|冷却辊|production',
  'vacuum|/ˈvækjuːm/|真空|production',
  'trial run|/ˈtraɪəl rʌn/|试机|production',
  'changeover|/ˈtʃeɪndʒəʊvə/|换产|production',
  'downtime|/ˈdaʊntaɪm/|停机时间|production',
  'batch consistency|/bætʃ kənˈsɪstənsi/|批次一致性|quality',
  'COA|/ˌsiː əʊ ˈeɪ/|分析证书|quality',
  'TDS|/ˌtiː diː ˈes/|技术数据表|quality',
  'SDS|/ˌes diː ˈes/|安全数据表|quality',
  'haze|/heɪz/|雾度|quality',
  'yellow index|/ˈjeləʊ ˈɪndeks/|黄度指数|quality',
  'color difference|/ˈkʌlə ˈdɪfrəns/|色差|quality',
  'transmittance|/trænzˈmɪtəns/|透光率|quality',
  'coefficient of friction|/ˌkəʊɪˈfɪʃənt əv ˈfrɪkʃən/|摩擦系数|quality',
  'surface tension|/ˈsɜːfɪs ˈtenʃən/|表面张力|quality',
  'tensile strength|/ˈtensaɪl streŋθ/|拉伸强度|quality',
  'elongation at break|/ˌiːlɒŋˈɡeɪʃən æt breɪk/|断裂伸长率|quality',
  'impact resistance|/ˈɪmpækt rɪˈzɪstəns/|耐冲击性|quality',
  'black spot|/blæk spɒt/|黑点|quality',
  'crystal point|/ˈkrɪstəl pɔɪnt/|晶点|quality',
  'streak|/striːk/|条纹|quality',
  'contamination|/kənˌtæmɪˈneɪʃən/|污染/杂质|quality',
  'defect|/ˈdiːfekt/|缺陷|quality',
  'tolerance|/ˈtɒlərəns/|公差|quality',
  'specification|/ˌspesɪfɪˈkeɪʃən/|规格要求|quality',
  'test method|/test ˈmeθəd/|测试方法|quality',
  'traceability|/ˌtreɪsəˈbɪləti/|可追溯性|quality',
  'shelf life|/ʃelf laɪf/|保质期|quality',
  'complaint|/kəmˈpleɪnt/|客诉|quality',
  'root cause|/ruːt kɔːz/|根本原因|quality',
  'corrective action|/kəˈrektɪv ˈækʃən/|纠正措施|quality',
  'inquiry|/ɪnˈkwaɪəri/|询盘|business',
  'quotation|/kwəʊˈteɪʃən/|报价单|business',
  'sample|/ˈsɑːmpəl/|样品|business',
  'trial order|/ˈtraɪəl ˈɔːdə/|试订单|business',
  'purchase order|/ˈpɜːtʃəs ˈɔːdə/|采购订单|business',
  'MOQ|/ˌem əʊ ˈkjuː/|最小起订量|business',
  'lead time|/liːd taɪm/|交期|business',
  'payment terms|/ˈpeɪmənt tɜːmz/|付款条件|business',
  'unit price|/ˈjuːnɪt praɪs/|单价|business',
  'target price|/ˈtɑːɡɪt praɪs/|目标价格|business',
  'discount|/ˈdɪskaʊnt/|折扣|business',
  'distributor|/dɪˈstrɪbjətə/|经销商|business',
  'end user|/end ˈjuːzə/|终端用户|business',
  'application|/ˌæplɪˈkeɪʃən/|应用场景|business',
  'requirement|/rɪˈkwaɪəmənt/|需求/要求|business',
  'pain point|/peɪn pɔɪnt/|痛点|business',
  'technical support|/ˈteknɪkəl səˈpɔːt/|技术支持|business',
  'follow up|/ˈfɒləʊ ʌp/|跟进|business',
  'feedback|/ˈfiːdbæk/|反馈|business',
  'approval|/əˈpruːvəl/|认可/批准|business',
  'annual demand|/ˈænjuəl dɪˈmɑːnd/|年需求量|business',
  'forecast|/ˈfɔːkɑːst/|需求预测|business',
  'shipment|/ˈʃɪpmənt/|出货/货运批次|business',
  'freight|/freɪt/|运费/货运|business',
  'packing list|/ˈpækɪŋ lɪst/|装箱单|business',
  'commercial invoice|/kəˈmɜːʃəl ˈɪnvɔɪs/|商业发票|business',
  'HS code|/ˌeɪtʃ ˈes kəʊd/|海关编码|business',
  'customs clearance|/ˈkʌstəmz ˈklɪərəns/|清关|business',
  'certificate of origin|/səˈtɪfɪkət əv ˈɒrɪdʒɪn/|原产地证|business',
  'Incoterms|/ˈɪŋkəʊtɜːmz/|国际贸易术语|business',
  'FOB|/ˌef əʊ ˈbiː/|离岸价|business',
  'CIF|/ˌsiː aɪ ˈef/|成本加保险费加运费|business',
  'EXW|/ˌiː eks ˈdʌbəljuː/|工厂交货价|business',
  'deposit|/dɪˈpɒzɪt/|定金|business',
  'balance payment|/ˈbæləns ˈpeɪmənt/|尾款|business',
  'delivery date|/dɪˈlɪvəri deɪt/|交货日期|business',
  'after-sales service|/ˌɑːftə seɪlz ˈsɜːvɪs/|售后服务|business',
  'filament|/ˈfɪləmənt/|3D 打印线材|printing',
  'spool|/spuːl/|线轴|printing',
  'nozzle|/ˈnɒzəl/|喷嘴|printing',
  'layer adhesion|/ˈleɪər ədˈhiːʒən/|层间附着力|printing',
  'warping|/ˈwɔːpɪŋ/|翘曲|printing',
  'stringing|/ˈstrɪŋɪŋ/|拉丝|printing',
  'print speed|/prɪnt spiːd/|打印速度|printing',
  'diameter tolerance|/daɪˈæmɪtə ˈtɒlərəns/|线径公差|printing',
  'roundness|/ˈraʊndnəs/|圆度|printing',
  'vacuum packaging|/ˈvækjuːm ˈpækɪdʒɪŋ/|真空包装|printing',
  'matte finish|/mæt ˈfɪnɪʃ/|哑光表面|printing',
  'high-speed printing|/haɪ spiːd ˈprɪntɪŋ/|高速打印|printing',
  'bed adhesion|/bed ədˈhiːʒən/|热床附着力|printing',
  'extrusion temperature|/ɪkˈstruːʒən ˈtemprətʃə/|挤出温度|printing',
  'dimensional stability|/daɪˈmenʃənəl stəˈbɪləti/|尺寸稳定性|printing',
  'carbon fiber reinforced|/ˈkɑːbən ˈfaɪbə ˌriːɪnˈfɔːst/|碳纤维增强|printing',
  'clogged nozzle|/klɒɡd ˈnɒzəl/|喷嘴堵塞|printing'
].join('\n');

